{
 "title": "Olist Delivery API",
 "panels": [
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "olist_http_requests_total" }
   ]
  },
  {
   "title": "Prediction results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "olist_predictions_total" }
   ]
  },
  {
   "title": "Average latency seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "olist_prediction_latency_seconds"
    }
   ]
  }
 ]
}